---
title: "EDA1"
author:
- Your Name 
date: 'July 28, 2023'
output:
  html_document:
    code_folding: show
    highlight: haddock
    number_sections: yes
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: '4'
  word_document:
    toc: yes
    toc_depth: '4'
urlcolor: blue
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(ISLR, readxl, tidyverse, tm, magrittr, dplyr, data.table, ggplot2, ggrepel)


install.packages("ggrepel")  # If you haven't installed the ggrepel package
install.packages("extrafont")  # If you haven't installed the extrafont package

library(ggrepel)
library(extrafont)
font_import("against.ttf")
loadfonts()
```

Import the data

```{r cars}
hap_data <- fread("data/WorldHappiness.csv", header = T, stringsAsFactors = F)
```

EDA

```{r pressure, echo=FALSE}
hap_data
hap_data <- rename(hap_data, country = Country, year = Year, gov_trust = government_trust)
hap_data$country
hap_data %>%
  group_by(country) %>%
  summarize(sum = n())

unique(hap_data%>%
  group_by(continent, country) %>%
  summarize(country = country))

mean_gdp <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), gdp_per_capita = mean(gdp_per_capita)) %>%
  arrange(desc(mean_happiness_score))

mean_gdp

ggplot(mean_gdp, aes(x = gdp_per_capita, y = mean_happiness_score, color = mean_happiness_score)) +
  geom_point(color = "grey") +
  geom_text_repel(data = subset(mean_gdp, country %in% c("China")), aes(label = country), color = "red", size = 4, fontface = "bold") +
  geom_point(data = subset(mean_gdp, country == "China"), aes(x = gdp_per_capita, y = mean_happiness_score), color = "red")
```

```{r Mean GDP}

mean_gdp <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), gdp_per_capita = mean(gdp_per_capita)) %>%
  arrange(desc(mean_happiness_score))

mean_gdp

fit_mean_gdp <- lm(mean_happiness_score ~ gdp_per_capita, data = mean_gdp) #fitting simple linear regression
summary(fit_mean_gdp) #summary of fit

mean_gdp_coef <- coef(summary(fit_mean_gdp))
mean_gdp_coef[1,1] #Intercept
mean_gdp_coef[2,1] #Slope

ggplot(mean_gdp, aes(x = gdp_per_capita, y = mean_happiness_score)) +
  geom_text_repel(aes(x = gdp_per_capita, y = mean_happiness_score, label = country), color = "#26ac6b", size = 2, max.overlaps = 15)+
  geom_point(aes(x = gdp_per_capita, y = mean_happiness_score), color = "#26ac6b") + 
  geom_abline(intercept = mean_gdp_coef[1,1], slope = mean_gdp_coef[2,1], color = "#ff6961") + 
  theme(panel.background = element_rect(fill = "#112333"))+ labs(
        x = "Mean GDP Per Capita (Hundreds of Thousands of Dollars)",
        y = "Mean Happiness Score 2015-2020") + 
   ggtitle("Mean Happiness Score vs Mean GDP Per Capita") +   # Set the title using ggtitle()
  theme(plot.title = element_text(hjust = 0.5, size = 12), axis.title = element_text(hjust = 0.5, size = 8), axis.text = element_text(hjust = 0.5, size = 4)) + 
  scale_x_continuous(breaks = seq(0, 2, by = 0.4),   # Customize x-axis breaks (intervals)
                     minor_breaks = seq(0, 2, by = 0.1),  # Customize x-axis minor breaks (intervals)
                     limits = c(0, 2),         # Customize x-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the x-axis
  scale_y_continuous(breaks = seq(2, 8, by = 1),   # Customize y-axis breaks (intervals)
                     minor_breaks = seq(2, 8, by = 0.5),  # Customize y-axis minor breaks (intervals)
                     limits = c(2, 8),         # Customize y-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the y-axis
  theme(panel.grid.major = element_line(color = "beige", size = 0.5),  # Customize major gridlines
        panel.grid.minor = element_line(color = "beige", size = 0.25))  # Customize minor gridlines
 # geom_text_repel(aes(x = payroll, y = win, label=team), size=3)
```

```{r Mean Health}

mean_health <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), health = mean(health)) %>%
  arrange(desc(mean_happiness_score))

mean_health

fit_mean_health <- lm(mean_happiness_score ~ health, data = mean_health) #fitting simple linear regression
summary(fit_mean_health) #summary of fit

mean_health_coef <- coef(summary(fit_mean_health))
mean_health_coef[1,1] #Intercept
mean_health_coef[2,1] #Slope

ggplot(mean_health, aes(x = health, y = mean_happiness_score)) +
  geom_text_repel(aes(x = health, y = mean_happiness_score, label = country), color = "#26ac6b", size = 2, max.overlaps = 17)+
  geom_point(aes(x = health, y = mean_happiness_score), color = "#26ac6b") + 
  geom_abline(intercept = mean_health_coef[1,1], slope = mean_health_coef[2,1], color = "#ff6961") + 
  theme(panel.background = element_rect(fill = "#112333"))+ labs(
        x = "Mean Health Coefficient",
        y = "Mean Happiness Score 2015-2020") + 
   ggtitle("Mean Happiness Score vs Mean Health") +   # Set the title using ggtitle()
  theme(plot.title = element_text(hjust = 0.5, size = 12), axis.title = element_text(hjust = 0.5, size = 8), axis.text = element_text(hjust = 0.5, size = 4)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.2),   # Customize x-axis breaks (intervals)
                     minor_breaks = seq(0, 1, by = 0.2),  # Customize x-axis minor breaks (intervals)
                     limits = c(0, 1),         # Customize x-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the x-axis
  scale_y_continuous(breaks = seq(2, 8, by = 1),   # Customize y-axis breaks (intervals)
                     minor_breaks = seq(2, 8, by = 0.5),  # Customize y-axis minor breaks (intervals)
                     limits = c(2, 8),         # Customize y-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the y-axis
  theme(panel.grid.major = element_line(color = "beige", size = 0.5),  # Customize major gridlines
        panel.grid.minor = element_line(color = "beige", size = 0.25))  # Customize minor gridlines
 # geom_text_repel(aes(x = payroll, y = win, label=team), size=3)
```

```{r Mean Freedom}

mean_freedom <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), freedom = mean(freedom)) %>%
  arrange(desc(mean_happiness_score))

mean_freedom

fit_mean_freedom <- lm(mean_happiness_score ~ freedom, data = mean_freedom) #fitting simple linear regression
summary(fit_mean_freedom) #summary of fit

mean_freedom_coef <- coef(summary(fit_mean_freedom))
mean_freedom_coef[1,1] #Intercept
mean_freedom_coef[2,1] #Slope

ggplot(mean_freedom, aes(x = freedom, y = mean_happiness_score)) +
  geom_text_repel(aes(x = freedom, y = mean_happiness_score, label = country), color = "#26ac6b", size = 2, max.overlaps = 17)+
  geom_point(aes(x = freedom, y = mean_happiness_score), color = "#26ac6b") + 
  geom_abline(intercept = mean_freedom_coef[1,1], slope = mean_freedom_coef[2,1], color = "#ff6961") + 
  theme(panel.background = element_rect(fill = "#112333"))+ labs(
        x = "Mean Freedom Coefficient",
        y = "Mean Happiness Score 2015-2020") + 
   ggtitle("Mean Happiness Score vs Mean Freedom") +   # Set the title using ggtitle()
  theme(plot.title = element_text(hjust = 0.5, size = 12), axis.title = element_text(hjust = 0.5, size = 8), axis.text = element_text(hjust = 0.5, size = 4)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.2),   # Customize x-axis breaks (intervals)
                     minor_breaks = seq(0, 1, by = 0.2),  # Customize x-axis minor breaks (intervals)
                     limits = c(0, 1),         # Customize x-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the x-axis
  scale_y_continuous(breaks = seq(2, 8, by = 1),   # Customize y-axis breaks (intervals)
                     minor_breaks = seq(2, 8, by = 0.5),  # Customize y-axis minor breaks (intervals)
                     limits = c(2, 8),         # Customize y-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the y-axis
  theme(panel.grid.major = element_line(color = "beige", size = 0.5),  # Customize major gridlines
        panel.grid.minor = element_line(color = "beige", size = 0.25))  # Customize minor gridlines
 # geom_text_repel(aes(x = payroll, y = win, label=team), size=3)
```

```{r Mean Generosity}

mean_generosity <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), generosity = mean(generosity)) %>%
  arrange(desc(mean_happiness_score))

mean_generosity

fit_mean_generosity <- lm(mean_happiness_score ~ generosity, data = mean_generosity) #fitting simple linear regression
summary(fit_mean_generosity) #summary of fit

mean_generosity_coef <- coef(summary(fit_mean_generosity))
mean_generosity_coef[1,1] #Intercept
mean_generosity_coef[2,1] #Slope

ggplot(mean_generosity, aes(x = generosity, y = mean_happiness_score)) +
  geom_text_repel(aes(x = generosity, y = mean_happiness_score, label = country), color = "#26ac6b", size = 2, max.overlaps = 17)+
  geom_point(aes(x = generosity, y = mean_happiness_score), color = "#26ac6b") + 
  geom_abline(intercept = mean_generosity_coef[1,1], slope = mean_generosity_coef[2,1], color = "#ff6961") + 
  theme(panel.background = element_rect(fill = "#112333"))+ labs(
        x = "Mean Generosity Coefficient",
        y = "Mean Happiness Score 2015-2020") + 
   ggtitle("Mean Happiness Score vs Mean Generosity") +   # Set the title using ggtitle()
  theme(plot.title = element_text(hjust = 0.5, size = 12), axis.title = element_text(hjust = 0.5, size = 8), axis.text = element_text(hjust = 0.5, size = 4)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.2),   # Customize x-axis breaks (intervals)
                     minor_breaks = seq(0, 1, by = 0.2),  # Customize x-axis minor breaks (intervals)
                     limits = c(0, 1),         # Customize x-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the x-axis
  scale_y_continuous(breaks = seq(2, 8, by = 1),   # Customize y-axis breaks (intervals)
                     minor_breaks = seq(2, 8, by = 0.5),  # Customize y-axis minor breaks (intervals)
                     limits = c(2, 8),         # Customize y-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the y-axis
  theme(panel.grid.major = element_line(color = "beige", size = 0.5),  # Customize major gridlines
        panel.grid.minor = element_line(color = "beige", size = 0.25))  # Customize minor gridlines
 # geom_text_repel(aes(x = payroll, y = win, label=team), size=3)
```

```{r Mean gov_trust}

mean_gov_trust <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), gov_trust = mean(gov_trust)) %>%
  arrange(desc(mean_happiness_score))

mean_gov_trust

fit_mean_gov_trust <- lm(mean_happiness_score ~ gov_trust, data = mean_gov_trust) #fitting simple linear regression
summary(fit_mean_gov_trust) #summary of fit

mean_gov_trust_coef <- coef(summary(fit_mean_gov_trust))
mean_gov_trust_coef[1,1] #Intercept
mean_gov_trust_coef[2,1] #Slope

ggplot(mean_gov_trust, aes(x = gov_trust, y = mean_happiness_score)) +
  geom_text_repel(aes(x = gov_trust, y = mean_happiness_score, label = country), color = "#26ac6b", size = 2, max.overlaps = 17)+
  geom_point(aes(x = gov_trust, y = mean_happiness_score), color = "#26ac6b") + 
  geom_abline(intercept = mean_gov_trust_coef[1,1], slope = mean_gov_trust_coef[2,1], color = "#ff6961") + 
  theme(panel.background = element_rect(fill = "#112333"))+ labs(
        x = "Mean Government Trust Coefficient",
        y = "Mean Happiness Score 2015-2020") + 
   ggtitle("Mean Happiness Score vs Mean Government Trust") +   # Set the title using ggtitle()
  theme(plot.title = element_text(hjust = 0.5, size = 12), axis.title = element_text(hjust = 0.5, size = 8), axis.text = element_text(hjust = 0.5, size = 4)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.2),   # Customize x-axis breaks (intervals)
                     minor_breaks = seq(0, 1, by = 0.2),  # Customize x-axis minor breaks (intervals)
                     limits = c(0, 1),         # Customize x-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the x-axis
  scale_y_continuous(breaks = seq(2, 8, by = 1),   # Customize y-axis breaks (intervals)
                     minor_breaks = seq(2, 8, by = 0.5),  # Customize y-axis minor breaks (intervals)
                     limits = c(2, 8),         # Customize y-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the y-axis
  theme(panel.grid.major = element_line(color = "beige", size = 0.5),  # Customize major gridlines
        panel.grid.minor = element_line(color = "beige", size = 0.25))  # Customize minor gridlines
 # geom_text_repel(aes(x = payroll, y = win, label=team), size=3)
```


```{r Mean social_support}

mean_social_support <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), social_support = mean(social_support)) %>%
  arrange(desc(mean_happiness_score))

mean_social_support

fit_mean_social_support <- lm(mean_happiness_score ~ social_support, data = mean_social_support) #fitting simple linear regression
summary(fit_mean_social_support) #summary of fit

mean_social_support_coef <- coef(summary(fit_mean_social_support))
mean_social_support_coef[1,1] #Intercept
mean_social_support_coef[2,1] #Slope

ggplot(mean_social_support, aes(x = social_support, y = mean_happiness_score)) +
  geom_text_repel(aes(x = social_support, y = mean_happiness_score, label = country), color = "#26ac6b", size = 2, max.overlaps = 17)+
  geom_point(aes(x = social_support, y = mean_happiness_score), color = "#26ac6b") + 
  geom_abline(intercept = mean_social_support_coef[1,1], slope = mean_social_support_coef[2,1], color = "#ff6961") + 
  theme(panel.background = element_rect(fill = "#112333"))+ labs(
        x = "Mean Social Support Coefficient",
        y = "Mean Happiness Score 2015-2020") + 
   ggtitle("Mean Happiness Score vs Mean Support") +   # Set the title using ggtitle()
  theme(plot.title = element_text(hjust = 0.5, size = 12), axis.title = element_text(hjust = 0.5, size = 8), axis.text = element_text(hjust = 0.5, size = 4)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.2),   # Customize x-axis breaks (intervals)
                     minor_breaks = seq(0, 1, by = 0.2),  # Customize x-axis minor breaks (intervals)
                     limits = c(0, 1),         # Customize x-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the x-axis
  scale_y_continuous(breaks = seq(2, 8, by = 1),   # Customize y-axis breaks (intervals)
                     minor_breaks = seq(2, 8, by = 0.5),  # Customize y-axis minor breaks (intervals)
                     limits = c(2, 8),         # Customize y-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the y-axis
  theme(panel.grid.major = element_line(color = "beige", size = 0.5),  # Customize major gridlines
        panel.grid.minor = element_line(color = "beige", size = 0.25))  # Customize minor gridlines
 # geom_text_repel(aes(x = payroll, y = win, label=team), size=3)
```


```{r Mean cpi_score}

mean_cpi_score <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), cpi_score = mean(cpi_score)) %>%
  arrange(desc(mean_happiness_score))

mean_cpi_score

fit_mean_cpi_score <- lm(mean_happiness_score ~ cpi_score, data = mean_cpi_score) #fitting simple linear regression
summary(fit_mean_cpi_score) #summary of fit

mean_cpi_score_coef <- coef(summary(fit_mean_cpi_score))
mean_cpi_score_coef[1,1] #Intercept
mean_cpi_score_coef[2,1] #Slope

ggplot(mean_cpi_score, aes(x = cpi_score, y = mean_happiness_score)) +
  geom_text_repel(aes(x = cpi_score, y = mean_happiness_score, label = country), color = "#26ac6b", size = 2, max.overlaps = 17)+
  geom_point(aes(x = cpi_score, y = mean_happiness_score), color = "#26ac6b") + 
  geom_abline(intercept = mean_cpi_score_coef[1,1], slope = mean_cpi_score_coef[2,1], color = "#ff6961") + 
  theme(panel.background = element_rect(fill = "#112333"))+ labs(
        x = "Mean CPI Score Coefficient",
        y = "Mean Happiness Score 2015-2020") + 
   ggtitle("Mean Happiness Score vs Mean CPI Score") +   # Set the title using ggtitle()
  theme(plot.title = element_text(hjust = 0.5, size = 12), axis.title = element_text(hjust = 0.5, size = 8), axis.text = element_text(hjust = 0.5, size = 4)) + 
  scale_x_continuous(breaks = seq(0, 100, by = 20),   # Customize x-axis breaks (intervals)
                     minor_breaks = seq(0, 100, by = 20),  # Customize x-axis minor breaks (intervals)
                     limits = c(0, 100),         # Customize x-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the x-axis
  scale_y_continuous(breaks = seq(2, 8, by = 1),   # Customize y-axis breaks (intervals)
                     minor_breaks = seq(2, 8, by = 0.5),  # Customize y-axis minor breaks (intervals)
                     limits = c(2, 8),         # Customize y-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the y-axis
  theme(panel.grid.major = element_line(color = "beige", size = 0.5),  # Customize major gridlines
        panel.grid.minor = element_line(color = "beige", size = 0.25))  # Customize minor gridlines
 # geom_text_repel(aes(x = payroll, y = win, label=team), size=3)
```

```{r first multiple linear regression model without corruption}

final.fit.1 <- lm(happiness_score ~ gdp_per_capita + health + freedom + generosity + gov_trust + social_support, data = hap_data)

summary(final.fit.1)
plot(final.fit.1)
```

```{r}
X <- as.matrix(hap_data[, c("gdp_per_capita", "health", "freedom", "generosity", "gov_trust", "social_support")])
X <- scale(X)
Y <- as.vector(hap_data$happiness_score)

lasso_model <- cv.glmnet(X, Y, alpha = 1)

optimal_lambda <- lasso_model$lambda.min

final_lasso_model <- glmnet(X, y, alpha = 1, lambda = optimal_lambda)

summary(final_lasso_model)
```


```{r moving spaghetti }

```

```{r}
country_data <- fread("data/world-data-2023.csv", header = T, stringsAsFactors = F)
country_data
```

```{r}
country_data <- subset(country_data, select = -V1)

#NA removal
#country_data <- select(country_data,-V1)

is.na(country_data)

na_counts <- colSums(is.na(country_data))
na_cols <- select(country_data,names(na_counts[na_counts > 0]))
colSums(is.na(na_cols))

na_row_tf <- apply(is.na(country_data), 1, any)
na_row_tf <- !na_row_tf
no_na_rows <- which(na_row_tf)

no_na_country_data <- country_data[no_na_rows, ]

sum(is.na(no_na_country_data))

no_na_country_data

fit.mul <- lm(happiness_score ~ . - country, data = no_na_country_data)
car::Anova(fit.mul)

plot(fit.mul, 1:2)

summary(fit.mul)
```


```{r}
fit.backward.1 <- update(fit.mul, .~. - infant_mortality)
car::Anova(fit.backward.1)
```

```{r}
fit.backward.2 <- update(fit.backward.1, .~. - tax_revenue)
car::Anova(fit.backward.2)
```


```{r}
fit.backward.3 <- update(fit.backward.2, .~. - land_area)
car::Anova(fit.backward.3)
```

```{r}
fit.backward.4 <- update(fit.backward.3, .~. - gdp)
car::Anova(fit.backward.4)
```

```{r}
fit.backward.5 <- update(fit.backward.4, .~. - cpi_change)
car::Anova(fit.backward.5)
```

```{r}
fit.backward.6 <- update(fit.backward.5, .~. - total_tax)
car::Anova(fit.backward.6)
```

```{r}
fit.backward.7 <- update(fit.backward.6, .~. - gasoline_price)
car::Anova(fit.backward.7)
```

```{r}
fit.backward.8 <- update(fit.backward.7, .~. - carbon_emissions)
car::Anova(fit.backward.8)
```

```{r}
fit.backward.9 <- update(fit.backward.8, .~. - population)
car::Anova(fit.backward.9)
```

```{r}
fit.backward.10 <- update(fit.backward.9, .~. - birth_rate)
car::Anova(fit.backward.10)
```

```{r}
fit.backward.11 <- update(fit.backward.10, .~. - fertility_rate)
car::Anova(fit.backward.11)
```

```{r}
fit.backward.12 <- update(fit.backward.11, .~. - primary_edu_enrollment)
car::Anova(fit.backward.12)
```

```{r}
fit.backward.13 <- update(fit.backward.12, .~. - latitude)
car::Anova(fit.backward.13)
```

```{r}
fit.backward.14 <- update(fit.backward.13, .~. - labor_force)
car::Anova(fit.backward.14)
```

```{r}
fit.backward.15 <- update(fit.backward.14, .~. - agricultural_land)
car::Anova(fit.backward.15)
```

```{r}
fit.backward.16 <- update(fit.backward.15, .~. - density)
car::Anova(fit.backward.16)
```

```{r}
fit.backward.17 <- update(fit.backward.16, .~. - pocket_health_expenditure)
car::Anova(fit.backward.17)
```

```{r}
fit.backward.18 <- update(fit.backward.17, .~. - cpi)
car::Anova(fit.backward.18)
```

```{r}
fit.backward.19 <- update(fit.backward.18, .~. - physicians_per_thousand)
car::Anova(fit.backward.19)
```

```{r}
summary(fit.backward.19)
```


```{r}
plot(fit.backward.19, 1:2)
```

```{r}
library(glmnet)

X <- as.matrix(no_na_country_data[, c("armed_forces", "forested_area", "tertiary_edu_enrollment", "life_expectancy", "maternal_mortality", "minimum_wage", "unemployment_rate", "urban_population", "longitude")])

X <- scale(X)

Y <- as.vector(no_na_country_data$happiness_score)

lasso.fit <- cv.glmnet(X, Y, alpha = 1, nfolds = 10)

summary(lasso.fit)

lambda.min <- lasso.fit$lambda.min

lambda.1se <- lasso.fit$lambda.1se

lasso.coef <- coef(lasso.fit, s = lambda.min)

lambda.min
lambda.1se
lasso.coef
```
$$y_{pred}=5.513-0.328x_{af}+0.161x_{fa}+0.382x_{tee}-0.291x_{le}-0.565x_{mm}+0.407x_{mw}-0.244x_{ur}+0.298x_{up}-0.234x_{l}$$

```{r}
agg_data <- country_data %>%
  reframe(happiness_score, armed_forces, forested_area, tertiary_edu_enrollment, life_expectancy, maternal_mortality, minimum_wage, unemployment_rate, urban_population, longitude)

is.na(agg_data)

na_counts <- colSums(is.na(agg_data))
na_cols <- select(agg_data,names(na_counts[na_counts > 0]))
colSums(is.na(na_cols))

na_row_tf <- apply(is.na(agg_data), 1, any)
na_row_tf <- !na_row_tf
no_na_rows <- which(na_row_tf)

no_na_agg_data <- agg_data[no_na_rows, ]

sum(is.na(no_na_agg_data))

no_na_agg_data
```
```{r}
set.seed(69)
n <- nrow(no_na_agg_data)
ind <- sample(n, 90)
agg_data_train <- no_na_agg_data[ind,]
agg_data_test <- no_na_agg_data[-ind,]

agg_data_test <- data.frame(agg_data_test)

model.trained <- lm(happiness_score ~ armed_forces + forested_area + tertiary_edu_enrollment + life_expectancy + maternal_mortality + minimum_wage + unemployment_rate + urban_population + longitude, data = agg_data_train)

agg_data_pred_test <- predict(model.trained, agg_data_test)
agg_data_pred_train <- predict(model.trained, agg_data_train)

agg_data_res_test <- agg_data_test$happiness_score - agg_data_pred_test
agg_data_res_train <- agg_data_train$happiness_score - agg_data_pred_train

mean(agg_data_res_test)
mean(agg_data_res_train)
```

```{r}
set.seed(10)

lasso.cv <- cv.glmnet(X, Y, alpha=1, nfolds=10)

plot(lasso.cv)
```

```{r}
4.17
country_data[33]
5.513-0.328*41000+0.161*50.2+0.382*44.9-0.291*76.8-0.565*59+0.407*2.46-0.244*3.97+0.298*11116711-0.234*(-78.1834)

fit.lm <- lm(happiness_score ~ armed_forces + forested_area + tertiary_edu_enrollment + life_expectancy + maternal_mortality + minimum_wage + unemployment_rate + urban_population + longitude, data = country_data)

country_data_df <- data.frame(country_data[33])

test_ecuador <- country_data_df[c("armed_forces", "forested_area", "tertiary_edu_enrollment", "life_expectancy", "maternal_mortality", "minimum_wage", "unemployment_rate", "urban_population", "longitude")]

class(test_ecuador)

predict(fit.lm, test_ecuador)
```

