---
title: "Analyzing World Happiness Scores and Predicting Global Happiness Decline"
author: Ritwij Ghosh, Jeesung Lee, Felix Liu, Dmitrios Zhao, Steven Kwon
date: 'August 4, 2023'
output:
  html_document:
    code_folding: show
    highlight: haddock
    number_sections: yes
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: '4'
  word_document:
    toc: yes
    toc_depth: '4'
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if(!require('pacman')) {install.packages('pacman')}
pacman::p_load(ISLR, readxl, tidyverse, tm, magrittr, dplyr, data.table, ggplot2, ggrepel)

options(repos = c(CRAN = "https://cran.r-project.org"))
install.packages("ggrepel")  # If you haven't installed the ggrepel package
install.packages("extrafont")  # If you haven't installed the extrafont package
install.packages("plotly")
library(plotly)
install.packages("rworldmap")
library(rworldmap)

library(ggrepel)
library(extrafont)
font_import("against.ttf")
loadfonts()
```

Import the data

```{r cars}
hap_data <- fread("data/WorldHappiness.csv", header = T, stringsAsFactors = F)
country_data <- fread("data/world-data-2023.csv", header = T, stringsAsFactors = F)
```

EDA

```{r pressure, echo=FALSE}
hap_data
hap_data <- rename(hap_data, country = Country, year = Year, gov_trust = government_trust)
hap_data$country
hap_data %>%
  group_by(country) %>%
  summarize(sum = n())

unique(hap_data%>%
  group_by(continent, country) %>%
  summarize(country = country))

mean_gdp <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), gdp_per_capita = mean(gdp_per_capita)) %>%
  arrange(desc(mean_happiness_score))

mean_gdp

ggplot(mean_gdp, aes(x = gdp_per_capita, y = mean_happiness_score, color = mean_happiness_score)) +
  geom_point(color = "grey") +
  geom_text_repel(data = subset(mean_gdp, country %in% c("China")), aes(label = country), color = "red", size = 4, fontface = "bold") +
  geom_point(data = subset(mean_gdp, country == "China"), aes(x = gdp_per_capita, y = mean_happiness_score), color = "red")
```

```{r Mean GDP}

mean_gdp <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), gdp_per_capita = mean(gdp_per_capita)) %>%
  arrange(desc(mean_happiness_score))

mean_gdp

fit_mean_gdp <- lm(mean_happiness_score ~ gdp_per_capita, data = mean_gdp) #fitting simple linear regression
summary(fit_mean_gdp) #summary of fit

mean_gdp_coef <- coef(summary(fit_mean_gdp))
mean_gdp_coef[1,1] #Intercept
mean_gdp_coef[2,1] #Slope

ggplot(mean_gdp, aes(x = gdp_per_capita, y = mean_happiness_score)) +
  geom_text_repel(aes(x = gdp_per_capita, y = mean_happiness_score, label = country), color = "#ee82ee", size = 2, max.overlaps = 17)+
  geom_point(aes(x = gdp_per_capita, y = mean_happiness_score), color = "#ee82ee") + 
  geom_abline(intercept = mean_gdp_coef[1,1], slope = mean_gdp_coef[2,1], color = "white") + 
  theme(panel.background = element_rect(fill = "#112333"))+ labs(
        x = "Mean GDP Per Capita (Hundreds of Thousands of Dollars)",
        y = "Mean Happiness Score 2015-2020") + 
   ggtitle("Mean Happiness Score vs Mean GDP Per Capita") +   # Set the title using ggtitle()
  theme(plot.title = element_text(hjust = 0.5, family = "against", size = 12), axis.title = element_text(hjust = 0.5, family = "against", size = 8), axis.text = element_text(hjust = 0.5, family = "against", size = 4)) + 
  scale_x_continuous(breaks = seq(0, 2, by = 0.4),   # Customize x-axis breaks (intervals)
                     minor_breaks = seq(0, 2, by = 0.1),  # Customize x-axis minor breaks (intervals)
                     limits = c(0, 2),         # Customize x-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the x-axis
  scale_y_continuous(breaks = seq(2, 8, by = 1),   # Customize y-axis breaks (intervals)
                     minor_breaks = seq(2, 8, by = 0.5),  # Customize y-axis minor breaks (intervals)
                     limits = c(2, 8),         # Customize y-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the y-axis
  theme(panel.grid.major = element_line(color = "beige", size = 0.5),  # Customize major gridlines
        panel.grid.minor = element_line(color = "beige", size = 0.25))  # Customize minor gridlines
 # geom_text_repel(aes(x = payroll, y = win, label=team), size=3)
```

```{r Mean Health}

mean_health <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), health = mean(health)) %>%
  arrange(desc(mean_happiness_score))

mean_health

fit_mean_health <- lm(mean_happiness_score ~ health, data = mean_health) #fitting simple linear regression
summary(fit_mean_health) #summary of fit

mean_health_coef <- coef(summary(fit_mean_health))
mean_health_coef[1,1] #Intercept
mean_health_coef[2,1] #Slope

ggplot(mean_health, aes(x = health, y = mean_happiness_score)) +
  geom_text_repel(aes(x = health, y = mean_happiness_score, label = country), color = "#ee82ee", size = 2, max.overlaps = 17)+
  geom_point(aes(x = health, y = mean_happiness_score), color = "#ee82ee") + 
  geom_abline(intercept = mean_health_coef[1,1], slope = mean_health_coef[2,1], color = "white") + 
  theme(panel.background = element_rect(fill = "#112333"))+ labs(
        x = "Mean Health Coefficient",
        y = "Mean Happiness Score 2015-2020") + 
   ggtitle("Mean Happiness Score vs Mean Health") +   # Set the title using ggtitle()
  theme(plot.title = element_text(hjust = 0.5, family = "against", size = 12), axis.title = element_text(hjust = 0.5, family = "against", size = 8), axis.text = element_text(hjust = 0.5, family = "against", size = 4)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.2),   # Customize x-axis breaks (intervals)
                     minor_breaks = seq(0, 1, by = 0.2),  # Customize x-axis minor breaks (intervals)
                     limits = c(0, 1),         # Customize x-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the x-axis
  scale_y_continuous(breaks = seq(2, 8, by = 1),   # Customize y-axis breaks (intervals)
                     minor_breaks = seq(2, 8, by = 0.5),  # Customize y-axis minor breaks (intervals)
                     limits = c(2, 8),         # Customize y-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the y-axis
  theme(panel.grid.major = element_line(color = "beige", size = 0.5),  # Customize major gridlines
        panel.grid.minor = element_line(color = "beige", size = 0.25))  # Customize minor gridlines
 # geom_text_repel(aes(x = payroll, y = win, label=team), size=3)
```

```{r Mean Freedom}

mean_freedom <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), freedom = mean(freedom)) %>%
  arrange(desc(mean_happiness_score))

mean_freedom

fit_mean_freedom <- lm(mean_happiness_score ~ freedom, data = mean_freedom) #fitting simple linear regression
summary(fit_mean_freedom) #summary of fit

mean_freedom_coef <- coef(summary(fit_mean_freedom))
mean_freedom_coef[1,1] #Intercept
mean_freedom_coef[2,1] #Slope

ggplot(mean_freedom, aes(x = freedom, y = mean_happiness_score)) +
  geom_text_repel(aes(x = freedom, y = mean_happiness_score, label = country), color = "#ee82ee", size = 2, max.overlaps = 17)+
  geom_point(aes(x = freedom, y = mean_happiness_score), color = "#ee82ee") + 
  geom_abline(intercept = mean_freedom_coef[1,1], slope = mean_freedom_coef[2,1], color = "white") + 
  theme(panel.background = element_rect(fill = "#112333"))+ labs(
        x = "Mean Freedom Coefficient",
        y = "Mean Happiness Score 2015-2020") + 
   ggtitle("Mean Happiness Score vs Mean Freedom") +   # Set the title using ggtitle()
  theme(plot.title = element_text(hjust = 0.5, family = "against", size = 12), axis.title = element_text(hjust = 0.5, family = "against", size = 8), axis.text = element_text(hjust = 0.5, family = "against", size = 4)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.2),   # Customize x-axis breaks (intervals)
                     minor_breaks = seq(0, 1, by = 0.2),  # Customize x-axis minor breaks (intervals)
                     limits = c(0, 1),         # Customize x-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the x-axis
  scale_y_continuous(breaks = seq(2, 8, by = 1),   # Customize y-axis breaks (intervals)
                     minor_breaks = seq(2, 8, by = 0.5),  # Customize y-axis minor breaks (intervals)
                     limits = c(2, 8),         # Customize y-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the y-axis
  theme(panel.grid.major = element_line(color = "beige", size = 0.5),  # Customize major gridlines
        panel.grid.minor = element_line(color = "beige", size = 0.25))  # Customize minor gridlines
 # geom_text_repel(aes(x = payroll, y = win, label=team), size=3)
```

```{r Mean Generosity}

mean_generosity <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), generosity = mean(generosity)) %>%
  arrange(desc(mean_happiness_score))

mean_generosity

fit_mean_generosity <- lm(mean_happiness_score ~ generosity, data = mean_generosity) #fitting simple linear regression
summary(fit_mean_generosity) #summary of fit

mean_generosity_coef <- coef(summary(fit_mean_generosity))
mean_generosity_coef[1,1] #Intercept
mean_generosity_coef[2,1] #Slope

ggplot(mean_generosity, aes(x = generosity, y = mean_happiness_score)) +
  geom_text_repel(aes(x = generosity, y = mean_happiness_score, label = country), color = "#ee82ee", size = 2, max.overlaps = 17)+
  geom_point(aes(x = generosity, y = mean_happiness_score), color = "#ee82ee") + 
  geom_abline(intercept = mean_generosity_coef[1,1], slope = mean_generosity_coef[2,1], color = "white") + 
  theme(panel.background = element_rect(fill = "#112333"))+ labs(
        x = "Mean Generosity Coefficient",
        y = "Mean Happiness Score 2015-2020") + 
   ggtitle("Mean Happiness Score vs Mean Generosity") +   # Set the title using ggtitle()
  theme(plot.title = element_text(hjust = 0.5, family = "against", size = 12), axis.title = element_text(hjust = 0.5, family = "against", size = 8), axis.text = element_text(hjust = 0.5, family = "against", size = 4)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.2),   # Customize x-axis breaks (intervals)
                     minor_breaks = seq(0, 1, by = 0.2),  # Customize x-axis minor breaks (intervals)
                     limits = c(0, 1),         # Customize x-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the x-axis
  scale_y_continuous(breaks = seq(2, 8, by = 1),   # Customize y-axis breaks (intervals)
                     minor_breaks = seq(2, 8, by = 0.5),  # Customize y-axis minor breaks (intervals)
                     limits = c(2, 8),         # Customize y-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the y-axis
  theme(panel.grid.major = element_line(color = "beige", size = 0.5),  # Customize major gridlines
        panel.grid.minor = element_line(color = "beige", size = 0.25))  # Customize minor gridlines
 # geom_text_repel(aes(x = payroll, y = win, label=team), size=3)
```

```{r Mean gov_trust}

mean_gov_trust <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), gov_trust = mean(gov_trust)) %>%
  arrange(desc(mean_happiness_score))

mean_gov_trust

fit_mean_gov_trust <- lm(mean_happiness_score ~ gov_trust, data = mean_gov_trust) #fitting simple linear regression
summary(fit_mean_gov_trust) #summary of fit

mean_gov_trust_coef <- coef(summary(fit_mean_gov_trust))
mean_gov_trust_coef[1,1] #Intercept
mean_gov_trust_coef[2,1] #Slope

ggplot(mean_gov_trust, aes(x = gov_trust, y = mean_happiness_score)) +
  geom_text_repel(aes(x = gov_trust, y = mean_happiness_score, label = country), color = "#ee82ee", size = 2, max.overlaps = 17)+
  geom_point(aes(x = gov_trust, y = mean_happiness_score), color = "#ee82ee") + 
  geom_abline(intercept = mean_gov_trust_coef[1,1], slope = mean_gov_trust_coef[2,1], color = "white") + 
  theme(panel.background = element_rect(fill = "#112333"))+ labs(
        x = "Mean Government Trust Coefficient",
        y = "Mean Happiness Score 2015-2020") + 
   ggtitle("Mean Happiness Score vs Mean Government Trust") +   # Set the title using ggtitle()
  theme(plot.title = element_text(hjust = 0.5, family = "against", size = 12), axis.title = element_text(hjust = 0.5, family = "against", size = 8), axis.text = element_text(hjust = 0.5, family = "against", size = 4)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.2),   # Customize x-axis breaks (intervals)
                     minor_breaks = seq(0, 1, by = 0.2),  # Customize x-axis minor breaks (intervals)
                     limits = c(0, 1),         # Customize x-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the x-axis
  scale_y_continuous(breaks = seq(2, 8, by = 1),   # Customize y-axis breaks (intervals)
                     minor_breaks = seq(2, 8, by = 0.5),  # Customize y-axis minor breaks (intervals)
                     limits = c(2, 8),         # Customize y-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the y-axis
  theme(panel.grid.major = element_line(color = "beige", size = 0.5),  # Customize major gridlines
        panel.grid.minor = element_line(color = "beige", size = 0.25))  # Customize minor gridlines
 # geom_text_repel(aes(x = payroll, y = win, label=team), size=3)
```


```{r Mean social_support}

mean_social_support <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), social_support = mean(social_support)) %>%
  arrange(desc(mean_happiness_score))

mean_social_support

fit_mean_social_support <- lm(mean_happiness_score ~ social_support, data = mean_social_support) #fitting simple linear regression
summary(fit_mean_social_support) #summary of fit

mean_social_support_coef <- coef(summary(fit_mean_social_support))
mean_social_support_coef[1,1] #Intercept
mean_social_support_coef[2,1] #Slope

ggplot(mean_social_support, aes(x = social_support, y = mean_happiness_score)) +
  geom_text_repel(aes(x = social_support, y = mean_happiness_score, label = country), color = "#ee82ee", size = 2, max.overlaps = 17)+
  geom_point(aes(x = social_support, y = mean_happiness_score), color = "#ee82ee") + 
  geom_abline(intercept = mean_social_support_coef[1,1], slope = mean_social_support_coef[2,1], color = "white") + 
  theme(panel.background = element_rect(fill = "#112333"))+ labs(
        x = "Mean Social Support Coefficient",
        y = "Mean Happiness Score 2015-2020") + 
   ggtitle("Mean Happiness Score vs Mean Support") +   # Set the title using ggtitle()
  theme(plot.title = element_text(hjust = 0.5, family = "against", size = 12), axis.title = element_text(hjust = 0.5, family = "against", size = 8), axis.text = element_text(hjust = 0.5, family = "against", size = 4)) + 
  scale_x_continuous(breaks = seq(0, 1, by = 0.2),   # Customize x-axis breaks (intervals)
                     minor_breaks = seq(0, 1, by = 0.2),  # Customize x-axis minor breaks (intervals)
                     limits = c(0, 1),         # Customize x-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the x-axis
  scale_y_continuous(breaks = seq(2, 8, by = 1),   # Customize y-axis breaks (intervals)
                     minor_breaks = seq(2, 8, by = 0.5),  # Customize y-axis minor breaks (intervals)
                     limits = c(2, 8),         # Customize y-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the y-axis
  theme(panel.grid.major = element_line(color = "beige", size = 0.5),  # Customize major gridlines
        panel.grid.minor = element_line(color = "beige", size = 0.25))  # Customize minor gridlines
 # geom_text_repel(aes(x = payroll, y = win, label=team), size=3)
```


```{r Mean cpi_score}

mean_cpi_score <- hap_data %>%
  group_by(country) %>%
  reframe(mean_happiness_score = mean(happiness_score), cpi_score = mean(cpi_score)) %>%
  arrange(desc(mean_happiness_score))

mean_cpi_score

fit_mean_cpi_score <- lm(mean_happiness_score ~ cpi_score, data = mean_cpi_score) #fitting simple linear regression
summary(fit_mean_cpi_score) #summary of fit

mean_cpi_score_coef <- coef(summary(fit_mean_cpi_score))
mean_cpi_score_coef[1,1] #Intercept
mean_cpi_score_coef[2,1] #Slope

ggplot(mean_cpi_score, aes(x = cpi_score, y = mean_happiness_score)) +
  geom_text_repel(aes(x = cpi_score, y = mean_happiness_score, label = country), color = "#ee82ee", size = 2, max.overlaps = 17)+
  geom_point(aes(x = cpi_score, y = mean_happiness_score), color = "#ee82ee") + 
  geom_abline(intercept = mean_cpi_score_coef[1,1], slope = mean_cpi_score_coef[2,1], color = "white") + 
  theme(panel.background = element_rect(fill = "#112333"))+ labs(
        x = "Mean CPI Score Coefficient",
        y = "Mean Happiness Score 2015-2020") + 
   ggtitle("Mean Happiness Score vs Mean CPI Score") +   # Set the title using ggtitle()
  theme(plot.title = element_text(hjust = 0.5, family = "against", size = 12), axis.title = element_text(hjust = 0.5, family = "against", size = 8), axis.text = element_text(hjust = 0.5, family = "against", size = 4)) + 
  scale_x_continuous(breaks = seq(0, 100, by = 20),   # Customize x-axis breaks (intervals)
                     minor_breaks = seq(0, 100, by = 20),  # Customize x-axis minor breaks (intervals)
                     limits = c(0, 100),         # Customize x-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the x-axis
  scale_y_continuous(breaks = seq(2, 8, by = 1),   # Customize y-axis breaks (intervals)
                     minor_breaks = seq(2, 8, by = 0.5),  # Customize y-axis minor breaks (intervals)
                     limits = c(2, 8),         # Customize y-axis limits
                     expand = c(0, 0)) +      # Remove extra space around the y-axis
  theme(panel.grid.major = element_line(color = "beige", size = 0.5),  # Customize major gridlines
        panel.grid.minor = element_line(color = "beige", size = 0.25))  # Customize minor gridlines
 # geom_text_repel(aes(x = payroll, y = win, label=team), size=3)
```

```{r first multiple linear regression model without corruption}

final.fit.1 <- lm(happiness_score ~ gdp_per_capita + health + freedom + generosity + gov_trust + social_support, data = hap_data)

summary(final.fit.1)
plot(final.fit.1, 1:2)
```

```{r moving spaghetti gdp}

moving_plot_gdp <- ggplot(data = hap_data, aes(x = gdp_per_capita + health + freedom + generosity + gov_trust + social_support, y = happiness_score, frame = year, color = hap_data$continent), color = hap_data$continent) + geom_point() + stat_smooth(method = "lm", se = TRUE, color = "white", aes(group = 0)) + labs(title = "Happiness Score VS WHR Indicators", x = "Happiness Indicators", y = "Happiness ", fill = "Continent") + theme(panel.background = element_rect(fill = "#112333")) + theme(plot.title = element_text(hjust = 0.5, family = "against", size = 12), axis.title = element_text(hjust = 0.5, family = "against", size = 8), axis.text = element_text(hjust = 0.5, family = "against", size = 4))

ggplotly(moving_plot_gdp)
```


```{r Loading and Cleaning Wharton Data}

wgyp <- fread("data/wgypHappy.csv", header = T, stringsAsFactors = F)

names(wgyp)

wgyp_clean <- wgyp %>% 
  select(-1, -2, -3, -4)

names(wgyp_clean)

wgyp_prediction <- predict(final.fit.1, wgyp)
wgyp_prediction <- wgyp_prediction/10
wgyp_prediction
mean(wgyp_prediction)
max(wgyp_prediction)
min(wgyp_prediction)

wgyp_dsa <- wgyp %>%
  filter(program == "Data Science Academy")
wgyp_pred_dsa <- predict(final.fit.1, wgyp_dsa)
wgyp_pred_dsa <- wgyp_pred_dsa/10
mean(wgyp_pred_dsa)
max(wgyp_pred_dsa)
min(wgyp_pred_dsa)

wgyp_lbw <- wgyp %>%
  filter(program == "Leadership in the Business World")
wgyp_pred_lbw <- predict(final.fit.1, wgyp_lbw)
wgyp_pred_lbw <- wgyp_pred_lbw/10
mean(wgyp_pred_lbw)
max(wgyp_pred_lbw)
min(wgyp_pred_lbw)

wgyp_usa <- wgyp %>%
  filter(in_usa == "Yes")
wgyp_pred_usa <- predict(final.fit.1, wgyp_usa)
wgyp_pred_usa <- wgyp_pred_usa/10
mean(wgyp_pred_usa)
max(wgyp_pred_usa)
min(wgyp_pred_usa)

wgyp_nusa <- wgyp %>%
  filter(in_usa == "No")
wgyp_pred_nusa <- predict(final.fit.1, wgyp_nusa)
wgyp_pred_nusa <- wgyp_pred_nusa/10
mean(wgyp_pred_nusa)
max(wgyp_pred_nusa)
min(wgyp_pred_nusa)
```

```{r}
#NA removal
country_data <- select(country_data,-V1)

sum(is.na(country_data))

na_counts <- colSums(is.na(country_data))
na_cols <- select(country_data,names(na_counts[na_counts > 0]))
na.vals <- colSums(is.na(na_cols))

na.vals


na_row_tf <-  apply(is.na(country_data), 1, any)

na_rows <- which(na_row_tf)

na_row_tf <- !na_row_tf
no_na_rows <- which(na_row_tf)

na_rows <- country_data[na_rows, ]
na_rows

no_na_country_data <- country_data[no_na_rows, ]

sum(is.na(no_na_country_data))
```

```{r}
# This uses every variable
library(randomForest)
library(caret)

set.seed(7)

# Split the data into predictors (X) and target variable (Y)
X <- no_na_country_data %>% select(-happiness_score)
Y <- no_na_country_data$happiness_score

# Split the data into 70/30 testing/training sets
train_index <- createDataPartition(Y, p = 0.7, list = FALSE)
train_data <- X[train_index, ]
test_data <- X[-train_index, ]
train_target <- Y[train_index]
test_target <- Y[-train_index]

# Create a random forest model
rf_model <- randomForest(x = train_data, y = train_target, ntree = 100, importance = TRUE, proximity = TRUE)


# Cross Validation
ctrl <- trainControl(method = "cv", number = 5)  # 5-fold 
# Cross-validate the random forest model
cv_results <- train(x = X, y = Y, method = "rf", trControl = ctrl, tuneGrid = expand.grid(mtry = 2), preProc = c("center", "scale"))


# Print the summary of the random forest model
rf_model
cv_results
plot(rf_model)

# Print a plot of predictions vs. actuals

predictions <- predict(rf_model, newdata = test_data)
plot(test_target, predictions)
varImpPlot(rf_model)
```

```{r}
# This uses only the variables significant to 95%
library(randomForest)
library(caret)

set.seed(7)

significant_columns <- c("armed_forces", "forested_area", "tertiary_edu_enrollment", "life_expectancy", "maternal_mortality", "minimum_wage", "unemployment_rate", "urban_population", "longitude" )

# Split the data into predictors (X) and target variable (Y)
X <- select(no_na_country_data, all_of(significant_columns))
Y <- no_na_country_data$happiness_score

# Split the data into 70/30 testing/training sets
train_index <- createDataPartition(Y, p = 0.7, list = FALSE)
train_data <- X[train_index, ]
test_data <- X[-train_index, ]
train_target <- Y[train_index]
test_target <- Y[-train_index]


# Create a random forest model
rf_model <- randomForest(x = train_data, y = train_target, ntree = 100, importance = TRUE, proximity = TRUE)


# Cross Validation
ctrl <- trainControl(method = "cv", number = 5)  # 5-fold 
# Cross-validate the random forest model
cv_results <- train(x = X, y = Y, method = "rf", trControl = ctrl, tuneGrid = expand.grid(mtry = 2), preProc = c("center", "scale"))

# Print the summary of the random forest model
rf_model
cv_results
plot(rf_model)

# Print a plot of predictions vs. actuals

predictions <- predict(rf_model, newdata = test_data)
plot(test_target, predictions)
varImpPlot(rf_model)
```

```{r}
library(tree)
library(randomForest)
library(caret)

set.seed(7)


# Split the data into 70/30 testing/training sets
train_index <- createDataPartition(Y, p = 0.7, list = FALSE)
train_data <- X[train_index, ]
test_data <- X[-train_index, ]
happiness_score <- Y[train_index]
test_target <- Y[-train_index]
train <- cbind(happiness_score,train_data)

# Create a decision tree model
fit1 <- tree(happiness_score ~ ., data = train)

# Print the tree model
print(fit1)

# Plot the tree
plot(fit1)
text(fit1,srt=45,cex=0.5)

# Make predictions on the testing data
test_predictions <- predict(fit1, newdata = test_data)

# Calculate RMSE and R-squared for testing
test_rmse <- sqrt(mean((test_target - test_predictions)^2))
test_r_squared <- 1 - sum((test_target - test_predictions)^2) / sum((test_target - mean(test_target))^2)

cat("Testing RMSE:", test_rmse, "\n")
cat("Testing R-squared:", test_r_squared, "\n")
```
